# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20180510_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
