# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_auto_20180516_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='share.Comment'),
            preserve_default=False,
        ),
    ]
