# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0019_auto_20180517_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
