# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0021_delete_newsletterrecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='who_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
